import type { Metadata } from "next";
import { Acme, Inter, Protest_Revolution } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

const protest = Protest_Revolution({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-protest",
});

const acme = Acme({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-acme",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${protest.variable} ${acme.variable}`}
      >
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster position="top-right" reverseOrder={false} />
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
